### ISSUE TITLE
Work with third-party file manager

### ISSUE THREAD

**Issue by linsui** [RikyIsola/FileManagerUtils#3]
**Is your feature request related to a problem? Please describe.**
This app doesn't with third-party file manager Material Files. Is that possiable? Material Files can add directories from SAF so it works with e.g. Muzei. But FileManagerUtils's SFTP directory isn't in the document ui. I guess the SFTP provider is different aas it can be unmount.

**Comment by rikyiso01** [comment]
The SFTP isn't a directory in the sdcard, it is a different document's provider
At the moment Android doesn't allow third party apps like Material File Manager to get the access permission of a document tree that is on a different document's provider
For example Material Files can't access Google Drive but with the stock file manager you can access it

**Comment by linsui** [comment]
Thanks for your Answer!
